Throw exception when unable to open IMAP stream.
Fixes

```

Warning: imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}INBOX in Instagram\Auth\Checkpoint\ImapClient->getLastInstagramEmailContent() (line 103 of src/Instagram/Auth/Checkpoint/ImapClient.php)
TypeError: imap_num_msg() expects parameter 1 to be resource, bool given in imap_num_msg() (line 104 of src/Instagram/Auth/Checkpoint/ImapClient.php)

```

Signed-off-by: Jibran Ijaz <jibran.ijaz@gmail.com>